### ISSUE TITLE
Make docker images public

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/sygma-relayer#30]
For relaying partners to be able to run their own relayers we should make the docker images built on release public.

## Implementation details

Switch to dockerhub and make them public there.

**Comment by mpetrun5** [comment]
@rbadillap Do you have time to handle this?

**Comment by mpetrun5** [comment]
We could. For open-source projects both are free. I think it is just a habit for open-source projects to use Dockerhub because of discoverability, but we don't care too much about that so it is fine either way.

**Comment by MakMuftic** [comment]
We also need this so we can use it in example repository.

**Comment by rbadillap** [comment]
@eedygreen, to accomplish this task, we should change the GitHub workflows and ECS task definitions to point to GitHub Docker Registry instead of AWS ECR.

AWS offers the possibility to make public our docker images using the [AWS Public Gallery](https://gallery.ecr.aws/); you can discuss with the team if this is feasible or if they prefer using GitHub for that.

In both cases, the ECS task definition and the workflows should be adapted to this new way.
